// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtwcAPmlPYNDwu7QY4_MsCjRBIpLy6PnU',
    appId: '1:741696463066:web:33f270c8cb71f07b2045e3',
    messagingSenderId: '741696463066',
    projectId: 'brillo-7c690',
    authDomain: 'brillo-7c690.firebaseapp.com',
    databaseURL: 'https://brillo-7c690-default-rtdb.firebaseio.com',
    storageBucket: 'brillo-7c690.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIJ6MKUSX2ge3ZkRV7YrbdzRiwgv8p-4',
    appId: '1:741696463066:android:1e0d7acbee2d24292045e3',
    messagingSenderId: '741696463066',
    projectId: 'brillo-7c690',
    databaseURL: 'https://brillo-7c690-default-rtdb.firebaseio.com',
    storageBucket: 'brillo-7c690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJJ1BOWgoUJu73rZF6AHSrqOB0qc3Hpw',
    appId: '1:741696463066:ios:5303c3b1aa13064f2045e3',
    messagingSenderId: '741696463066',
    projectId: 'brillo-7c690',
    databaseURL: 'https://brillo-7c690-default-rtdb.firebaseio.com',
    storageBucket: 'brillo-7c690.appspot.com',
    iosBundleId: 'com.example.brillohn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJJ1BOWgoUJu73rZF6AHSrqOB0qc3Hpw',
    appId: '1:741696463066:ios:5303c3b1aa13064f2045e3',
    messagingSenderId: '741696463066',
    projectId: 'brillo-7c690',
    databaseURL: 'https://brillo-7c690-default-rtdb.firebaseio.com',
    storageBucket: 'brillo-7c690.appspot.com',
    iosBundleId: 'com.example.brillohn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtwcAPmlPYNDwu7QY4_MsCjRBIpLy6PnU',
    appId: '1:741696463066:web:76d67f129ca1cfbb2045e3',
    messagingSenderId: '741696463066',
    projectId: 'brillo-7c690',
    authDomain: 'brillo-7c690.firebaseapp.com',
    databaseURL: 'https://brillo-7c690-default-rtdb.firebaseio.com',
    storageBucket: 'brillo-7c690.appspot.com',
  );

}